### ISSUE TITLE
Looking for humanoid warrior species

### ISSUE THREAD

**Issue by manekinekko** [manekinekko/klingon#2]
The Klingon app needs you. If you wanna help, leave your name below 😎

**Comment by wpasternak** [comment]
Hey i would like to help 👍

**Comment by manekinekko** [comment]
Hi @wpasternak is there something you wanna help with in particular?

**Comment by lordKnighton** [comment]
@lordKnighton here  👍  🍺 
count me in, when i have free time I'd love to help with `docs` , `issues` 
preferably easy - mid for starters + maybe writing tutorials on `medium`  for quick starts

**Comment by SylvestreMassalaz** [comment]
Hey, if I can be of some assistance, I'm happy to help =)

**Comment by manekinekko** [comment]
thanks @lordKnighton and @SylvestreMassalaz please feel free to take any issue and send PRs :)
